### ISSUE TITLE
maybe there exits packet loss situation after apply pptmon

### ISSUE THREAD

**Issue by horser1** [dpnm-ni/ppt-mon#1]
I build a topo link this 
![8460f495b863e70eb4074492209aa4b](https://user-images.githubusercontent.com/48501653/226529673-56a5992b-9c12-4ff8-b042-089d6b278f69.jpg)
there are three containers(from left to right I call them 1,2,3), they are all host, and I specified the route table then the network is reachable
and I apply pptmon with source_sink mode in the middle container at eth2 and eth3 interface. 'python3 -m pptmon -i eth2 -o eth3 -m source_sink'
I raise iperf3 server in container 3,
### **the problem is:** 
**1.** when I raise iperf3 client in container 1 with udp, the iperf3 server report there exits one packet loss every second
iperf3 client:
![image](https://user-images.githubusercontent.com/48501653/226530804-655ba7c2-daee-49e7-b03b-8e6f8a24aa80.png)
iperf3 server:
![image](https://user-images.githubusercontent.com/48501653/226530873-a35a9c38-097e-4a22-9b76-8e683fabc83a.png)
and if I don't ckeck the sample time(it means it will deal with every packet),link below, I use a macro define 'IF_SAMPLE' to achieve it.
![image](https://user-images.githubusercontent.com/48501653/226531392-56395631-3a9d-4d3d-8e7d-b3544e790e50.png)
then the udp packet will all reported loss
iperf3 client:
![image](https://user-images.githubusercontent.com/48501653/226531604-b8c73ae2-9662-42a2-912a-e8ef441b5a41.png)
iperf3 server:
![image](https://user-images.githubusercontent.com/48501653/226531671-ed5457ad-fdef-4a4a-804c-e223e2fd1217.png)
so I suspect that  there is a problem with your package processing？
2. tcp is the same, in order to remove the influence of network congestion or low processing efficiency, I use tc to limit the bandwidth in eth1 interface in container 1(because the tc rules is added to eth1 in conainer1, so it will not influence pptmon which is in container2)
this is the iperf3 test(now not apply pptmon, just add tc to contianer1)
iperf3 client:
![image](https://user-images.githubusercontent.com/48501653/226532985-212d1d5c-d4bf-4e08-aa30-f8ae24506444.png)
iperf3 server:
![image](https://user-images.githubusercontent.com/48501653/226533042-38bb40cb-681b-46fe-ad31-36e2c4c11ae8.png)
 then I apply the pptmon(also no sample)
iperf3 client:
![image](https://user-images.githubusercontent.com/48501653/226533209-a50ef779-1ad0-449d-b435-a382c1f90277.png)
iperf3 server:
![image](https://user-images.githubusercontent.com/48501653/226533264-f4a3c59d-5403-4e46-bfe3-67c269a999a9.png)

you see, I have set a low bandwidth(10M), so the pps of tcp is low, so pptmon must can deal with it under this pps, but it also appear this problem.
I tried several CC algorithm but no use. So can you deal with this problem?
thanks!

**Comment by tu-nv** [comment]
Hi, since ppt-mon embeds data into the packet header, the packet + pptmon data should not be larger than MTU. can you try set packet size of IPerf to around 1200 and see if it fix the issue?

**Comment by horser1** [comment]
thanks, I have find it, and set the packet length up to 1400, and then work well. 
this means if the messages is fragmented, it will not be suiltable for packet time measurement?

**Comment by tu-nv** [comment]
Yes, currently, this is the limitation. A method to mitigate this issue is to just sample out these big packets, which work for normal traffics but not iperf (iperf always try to send packets as large as possible). However, we haven't implemented that into pptmon yet.

**Comment by horser1** [comment]
ok, I get it,thanks
